apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-app
spec:
    replicas: 2
    template:
        spec:
            containers:
                - name: eventscape-app
                  image: sodiumna11/eventscape-app:latest
                  imagePullPolicy: Always
                  # resources:
                  #     limits:
                  #         memory: 512Mi
                  #         cpu: 250m
                  #     requests:
                  #         memory: 256Mi
                  #         cpu: 100m
