apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - db-pv.yaml
    - db-pvc.yaml
    - db-deployment.yaml
    - db-service.yaml
    - app-deployment.yaml
    - app-service.yaml

configMapGenerator:
  - name: postgres-cm
    files:
      - db/schema.sql
      - db/seed.sql

generatorOptions:
  disableNameSuffixHash: true